### ISSUE TITLE
Unable to get an authenticated user from http request context

### ISSUE THREAD

**Issue by aloposov** [sogko/slumber#12]
Hi!
I'm using curl to test and get familiar with your rest API project. After modifying token claims code to comply with the latest jwt-go version, everything started working, but..
I was able to create a couple of users using api/users POST request and then create a session for a user by passing the jwt token in an authorization header. But when I try calling an API for listing users (and any other API that requires authentication, the following happens:
1) token verification goes fine
2) authenticated user is written into the request in authenticator.go using ctx.SetCurrentUserCtx(req, user)
3) then server is 'next'-ing and passes control to NewContextHandler function, which tries to get current user from the same request using this code:
user := ac.ctx.GetCurrentUserCtx(req)
...And gets nothing. What am I doing wrong?

**Comment by aloposov** [comment]
The problem is solved by rewriting the project to use new Go 1.7 http context. Basically, a new request has to be created when adding data to the context.

**Comment by SkyHacks** [comment]
Can you elaborate on how you were able to fix this problem? I'm running into the same issue.
